import type { LumenPlate } from "./model.ts";

export const LUMEN_PLATES: LumenPlate[] = [
  {
    id: "reflection",
    numeral: "I",
    title: "First Reflection",
    subtitle: "Specular study",
    note: "Turn the black-silver plane until the wandering beam finds its receiver.",
    hint: "A quiet mirror almost lies flat when it returns light upward.",
    emitter: { x: 100, y: 500, angle: -0.5586 },
    elements: [
      {
        id: "mirror-a",
        kind: "mirror",
        label: "M1",
        radius: 34,
        rotatable: true,
        start: { x: 420, y: 300, angle: 0.72 },
        solution: { x: 420, y: 300, angle: -0.026 },
      },
    ],
    targets: [
      { id: "receiver-a", x: 780, y: 500, radius: 24, label: "R1" },
    ],
  },
  {
    id: "refraction",
    numeral: "II",
    title: "Measured Bend",
    subtitle: "Collimation plate",
    note: "Rotate the lens axis. The aperture accepts only an exact line of light.",
    hint: "The receiver sits just below a twenty-two degree descent from the lens.",
    emitter: { x: 100, y: 140, angle: 0.4229 },
    elements: [
      {
        id: "lens-a",
        kind: "lens",
        label: "L1",
        radius: 34,
        rotatable: true,
        start: { x: 300, y: 230, angle: -0.38 },
        solution: { x: 300, y: 230, angle: 0.388 },
      },
      {
        id: "aperture-a",
        kind: "aperture",
        label: "A1",
        radius: 24,
        start: { x: 560, y: 336, angle: 0 },
        solution: { x: 560, y: 336, angle: 0 },
      },
    ],
    targets: [
      { id: "receiver-b", x: 800, y: 434, radius: 25, label: "R2" },
    ],
  },
  {
    id: "temperature",
    numeral: "III",
    title: "Temperature of Glass",
    subtitle: "Chromatic assay",
    note: "Place the oxide filter in the beam, then tune the lens to carry warmth onward.",
    hint: "The filter belongs on the central datum. The lens then points due east.",
    emitter: { x: 90, y: 310, angle: 0 },
    elements: [
      {
        id: "filter-a",
        kind: "filter",
        label: "F1",
        radius: 30,
        movable: true,
        color: "warm",
        start: { x: 410, y: 480, angle: 0 },
        solution: { x: 410, y: 310, angle: 0 },
      },
      {
        id: "lens-b",
        kind: "lens",
        label: "L2",
        radius: 32,
        rotatable: true,
        start: { x: 610, y: 310, angle: 0.46 },
        solution: { x: 610, y: 310, angle: 0 },
      },
    ],
    targets: [
      { id: "receiver-c", x: 810, y: 310, radius: 24, color: "warm", label: "R3" },
    ],
  },
  {
    id: "spectrum",
    numeral: "IV",
    title: "Two Frequencies",
    subtitle: "Prismatic division",
    note: "Rotate the prism until cool and warm light arrive as a balanced pair.",
    hint: "Balance begins when the prism's engraved axis is horizontal.",
    emitter: { x: 90, y: 310, angle: 0 },
    elements: [
      {
        id: "prism-a",
        kind: "prism",
        label: "P1",
        radius: 36,
        rotatable: true,
        split: 0.22,
        start: { x: 390, y: 310, angle: 0.55 },
        solution: { x: 390, y: 310, angle: 0 },
      },
    ],
    targets: [
      { id: "receiver-d1", x: 790, y: 220, radius: 25, color: "cool", label: "C" },
      { id: "receiver-d2", x: 790, y: 400, radius: 25, color: "warm", label: "W" },
    ],
  },
  {
    id: "synthesis",
    numeral: "V",
    title: "Synthesis in Crossing",
    subtitle: "Final instrument",
    note: "Divide the source, then turn both mirrors so the two colors exchange horizons.",
    hint: "The upper plane rises slightly; the lower answers with the inverse angle.",
    emitter: { x: 80, y: 310, angle: 0 },
    elements: [
      {
        id: "prism-b",
        kind: "prism",
        label: "P2",
        radius: 34,
        rotatable: true,
        split: 0.22,
        start: { x: 300, y: 310, angle: 0.42 },
        solution: { x: 300, y: 310, angle: 0 },
      },
      {
        id: "mirror-b1",
        kind: "mirror",
        label: "M2",
        radius: 34,
        rotatable: true,
        start: { x: 540, y: 256, angle: -0.62 },
        solution: { x: 540, y: 256, angle: 0.12 },
      },
      {
        id: "mirror-b2",
        kind: "mirror",
        label: "M3",
        radius: 34,
        rotatable: true,
        start: { x: 540, y: 364, angle: 0.64 },
        solution: { x: 540, y: 364, angle: -0.12 },
      },
    ],
    targets: [
      { id: "receiver-e1", x: 810, y: 390, radius: 26, color: "cool", label: "C2" },
      { id: "receiver-e2", x: 810, y: 230, radius: 26, color: "warm", label: "W2" },
    ],
  },
];
